project:
  type: website

website:
  title: "ESP32 DuckDNS"
  navbar:
    left:
      - text: "README"
        href: readme.md

format:
  html:
    theme:
      light: flatly   # Bootswatch theme (Bootstrap look)
    toc: true
    toc-location: left
    css: styles.css

