project:
  type: website

site-url: "https://toledoem.github.io/espduckdns/"

website:
  title: "ESP32 DuckDNS"
  navbar:
    left:
      - text: "Repository"
        href: "https://github.com/ToledoEM/duckdns_esp32"

format:
  html:
    theme:
      light: flatly # Bootswatch theme (Bootstrap look)
    includes:
      in_header: |
        <script data-goatcounter="https://etoledo.goatcounter.com/count"
          async src="//gc.zgo.at/count.js"></script>
    toc: true
    toc-location: left
    toc-depth: 4
    toc-expand: 2
    css: styles.css
